version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: backend-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # MinIO (Servidor de Arquivos compatível com S3)
  minio:
    image: minio/minio:latest
    container_name: backend-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - backend-network

  # Criação automática do bucket 'capas-albuns' no MinIO ao iniciar
  create-buckets:
    image: minio/mc
    container_name: backend-minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p myminio/capas-albuns || true;
      /usr/bin/mc anonymous set public myminio/capas-albuns || true;
      exit 0;
      "
    networks:
      - backend-network

  # API (Spring Boot)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    depends_on:
      - postgres
      - minio
      - create-buckets
    environment:
      SPRING_PROFILES_ACTIVE: docker

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/backend_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: capas-albuns

      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000

      JWT_SECRET: UmaChaveMuitoSecretaParaOProcessoSeletivoMatoGrosso2026
      JWT_EXPIRATION: 300000
      JWT_REFRESH_EXPIRATION: 2592000000

    ports:
      - "8080:8080"
    networks:
      - backend-network

volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
    driver: bridge
