version: '3.8'

services:
  # Banco de Dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: backend-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  # MinIO (Servidor de Arquivos compatível com S3)
  minio:
    image: minio/minio:latest
    container_name: backend-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web (Login: minioadmin / minioadmin)
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    networks:
      - backend-network

  # Criação automática do bucket 'capas-albuns' no MinIO ao iniciar
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/capas-albuns;
      /usr/bin/mc anonymous set public myminio/capas-albuns;
      exit 0;
      "
    networks:
      - backend-network

volumes:
  postgres_data:
  minio_data:

networks:
  backend-network:
    driver: bridge